### ISSUE TITLE
u5admin/delete.php

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#16]
This script is executed when clicking one of the letters D meaning Delete in the u5CMS backend. These letters D can be found in the very right column for each object.

The following error occurs:
Warning: Undefined array key "dora" in /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/u5admin/delete.php on line 2 Warning: Cannot modify header information - headers already sent by (output started at /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/u5admin/delete.php:2) in /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/u5admin/delete.php on line 3

**Comment by mrolli** [comment]
The code point is a cookie-based branching if, see [here](https://github.com/u5cms/u5cms/blob/6364cf09dc2ddbec4f19c60091a276ba7f4ca908/u5admin/delete.php#L2). This generates only a warning if dora is not in the $_COOKIE array and normally suppressed, therefore no error would occur. Such code places are quite often. Should I add an isset check to avoid the warning?

**Comment by stemind** [comment]
Yes, isset, thx.
