### ISSUE TITLE
/u5admin/mailingeditor.php fails to execute "view"

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#21]
In PIDVESA^s S -> formdata -> mail (on any entry) there is the link "Send serial mails to the above data selection" expanding the serial mail editor.

In the mail editor's very right column, sent and unsent serial mails are listed.

Sent ones offer the Link "view" (so a sent one has to be created for reproducing the error). View goes into the following error:

Fatal error: Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/u5admin/mailingeditor.php:91 Stack trace: #0 /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/u5admin/mailingeditor.php(91): date('Y-m-d H:i:s', '1637506415 by s...') #1 {main} thrown in /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/u5admin/mailingeditor.php on line 91

**Comment by mrolli** [comment]
Interesting code place... this actually never worked correctly. Note the parenthesis on [line91 in mailingeditor.php](https://github.com/u5cms/u5cms/blob/861969932e77d619bd6db0e654ac134b8a443e1a/u5admin/mailingeditor.php#L91).
