### ISSUE TITLE
/u5admin/import.php type error in date()

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#22]
The problem that in date()'s first parameter is a constant instead of a string (and in the second parameter a string instead of an int) is widely present in the PHP8-revision projects at hand, not only u5CMS. 

Therefore a regexed search for 
date(Y 
date(m
date(H
etc.
or more general
date(not a quote or apostrophe
could be interesting and further for date(anything comma quote or apostrophe.

The error at hand in import.php is
Fatal error: Uncaught Error: Undefined constant "YmdHis" in /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/u5admin/import.php:178
only visible in the HTML source code.

import.php is achievable in action as this:
u5CMS-Backend, PIDVESA's, Special functions, formdata, import from excel link there (bellow the table).

**Comment by mrolli** [comment]
Searched through using `git grep "date([^'\"$)]"`. Only this occurrence in `import.php`. Every other usage is safe, at least in the CMS.
