### ISSUE TITLE
Special chars in subject of new mailjobs not supported

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#33]
Bug already present in older versions.

When a new mailjob is started, javascript prompts for subject. If subject is entered with special characters e. g. ä it is evaluated as empty.

When the subject is entered without special characters and later on edited towards containing special characters, upper bank chars as  出 are rendered as visiblie HTML-entities in the very right overview column and in the subject field of the maileditor.

How to get there
- u5CMS backend
- PIDVESA's S -> Special functions -> formdata
- mydata5's mail-link
- Open mailjob-area with the link at the bottom of the page

**Comment by mrolli** [comment]
I'm able to reproduce the error when using directly upper bank chars, but works for me when adding such charachter later on The two cases illustrated when carried out in current `/_u5cm` version.


![preview](https://user-images.githubusercontent.com/292256/147740847-4df17cd2-dfb6-4507-a7ba-0f9ba53384d1.jpg)
