### ISSUE TITLE
u5sys.navigation.php

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#40]
When a rather complex navigation is built in u5CMS's backend (object named navigation in PIDVESA's P, std pages) rendering of the navigation in the frontend is faulty. Such a rather complex navigation can be copied and pasted from the txt-file contained in https://yuba.ch/r/navi/navi_en.zip.

In that zip-file there is also an alternate u5sys.navigation.php using JavaScript to render the tree context instead of pure PHP. The disadvantage of this solution is, that password protected subtrees are visible in the HTML code. If this shall be seen as a problem or not has to be defined.

For the new PHP8 compatible u5CMS 10 upwards the question arises, if the pure PHP u5sys.navigation.php shall be fixed or switched to the aforementioned alternate one.

**Comment by mrolli** [comment]
Fixed in #48
