### ISSUE TITLE
"show link of active language in meta navi"-feature never worked

### ISSUE THREAD

**Issue by mrolli** [u5cms/u5cms#46]
Please have a look into https://github.com/u5cms/u5cms/blob/dc808fe2fcdf557224ac9c8d53c73e556eff85e0/u5sys.languages.php#L9

This "show link of active langujage in meta navi"-feature actually never worked as the variable `$u5showlinkofactivelanguageinmetanavi` is only check in this file at three spot, but the entire CMS does never set it.

- Is this something that got forgotten in `config.php`? 
- Shall I add it to the configuration?
- If yes, does it default to `yes` or `no`?

**Comment by stemind** [comment]
Is must not be contained in the initial config. Can be added there on demand according to https://yuba.ch/index.php?c=u5econfigphp&l=en&q=showlink. Defaulting to the value depicted on the aforementioned page.
