### ISSUE TITLE
Variable $automaticallyskipbackendlogin never set but checked

### ISSUE THREAD

**Issue by mrolli** [u5cms/u5cms#47]
The follwoing line shows a check for which the variable is actually never set or settable in `config.php.sample`:

https://github.com/u5cms/u5cms/blob/dc808fe2fcdf557224ac9c8d53c73e556eff85e0/u5admin/usercheck.inc.php#L57

What should we do here? Is this something you add on demand to the config without being available by default?

**Comment by stemind** [comment]
Yes, it is added on demand to the config; cf. https://yuba.ch/index.php?c=u5econfigphp&l=en&q=skip
