### ISSUE TITLE
Wrong calculation logic in chart2.php

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#59]
The xya-installation brings to light a decades-old error: In the questionnaires results statistic rendering the percentage values in parentheses displayed on the right of each value bar is calculated with the overall big orange n instead of the n (participants) for this item.
Interestingly, the item specific n, calculated in the iframed mean.php there, would be the good one.

Therefore in chart2.php the n-calculation of mean.php has to be mimicked and used for the percentage calculation. However, I did not succeed in understanding how this could be done.

**Comment by mrolli** [comment]
This might be already fixed in 10.x release almost exactly a year ago, see commit 2ef1424ee602640c44a06a0c2796eff1f0c171e8

PHP-7.3 compatibility presupposed, this could be backported to branch 8.x. What do you think?
