### ISSUE TITLE
Class "SmtpOptions" not found

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#7]
After installing version 10 using the sample config.php distributed with the following error is desplayed when the the main page is opened in the browser:
Fatal error: Uncaught Error: Class "SmtpOptions" not found in /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/config.php:25 Stack trace: #0 /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/connect.inc.php(8): include() #1 /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/index.php(2): require_once('/home/httpd/vho...') #2 {main} thrown in /home/httpd/vhosts/stemind.ch/ilj.li/u5cms/config.php on line 25

**Comment by mrolli** [comment]
Interesting, as the class is actually contained in vendor/Laminas/... and it works fine on the testserver at least.

Could you please add the following line as the fist line in config.php:
```
use Laminas\Mail\Transport\SmtpOptions;
```

Does it then work?
Will look into it later if still not working.

**Comment by stemind** [comment]
With use Laminas\Mail\Transport\SmtpOptions; as first line in config.php it works fine. Could you add this line do release's config.dist.php? Thx
