### ISSUE TITLE
Schema migration in runonce.php not compatible with Mariadb-10.3.x

### ISSUE THREAD

**Issue by mrolli** [u5cms/u5cms#73]
On our servers, we run mariadb-10.3.35 and updating it to 10.5.2 or higher is
not an option. The current implementation of the schema change script in
runonce.php is using `ALTER TABLE t1 RENAME COLUMN c_old TO c_new;`. This syntax
is only supported since MariaDB 10.5.2.

To be backwards compatible, these `RENAME COLUMN` usages needed to be reverted
to `CHANGE COLUMN` syntax. CAVEAT: This latter syntax needs the full column defs
including type and features!

**Comment by vuphan-adnovumvn** [comment]
Hi @mrolli 
I will create a new PR to fix this issue today.
Regards,
Vu
